name: CI & Publish

on:
  push:
    branches:
      - release

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Получаем всю историю коммитов, включая теги

      - name: Get latest tag
        id: get_tag
        run: |
          # Получаем последний тег по дате создания
          LATEST_TAG=$(git describe --tags --abbrev=0)
          echo "Latest tag: $LATEST_TAG"
          echo "VERSION=$LATEST_TAG" >> $GITHUB_ENV
          echo "::set-output name=version::$LATEST_TAG"

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install NUKE
        run: dotnet tool install --global Nuke.GlobalTool

      - name: Run NUKE
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
          VERSION: ${{ env.VERSION }}  # Используем переменную окружения
        run: |
          export PATH="$PATH:$HOME/.dotnet/tools"
          nuke PublishNuget